### ISSUE TITLE
Example schema?

### ISSUE THREAD

**Issue by brylie** [meteor/data#2]
Is there an example of a GraphQL schema that the Meteor Data project will support? E.g. a simple example in the documentation would help clarify the expected use.

**Comment by batjko** [comment]
I'm sure the first thing to come out will be an example implementation for a Meteor Todos App, with a simple query and insert mutation for a tasks schema.

Looking forward to this, should be exciting!

**Comment by stubailo** [comment]
We want to be 100% interoperable with the "standard" GraphQL stuff - so if you get the reference JavaScript implementation and write a GraphQL resolver, our frontend will work with that out of the box, without reactivity.

To get reactivity, you will have to modify your resolvers to use our special database accessors, or emit data dependencies manually. Also, we expect to have some quality-of-life wrappers for GraphQL schema building for simple cases (for example, if your GraphQL schema exactly matches your SQL schema).

More details to come soon - we wanted to share our direction and goals as soon as possible, so we don't have a crisp design document yet. However, we are pretty sure of the direction so it's just a matter of time until we produce some materials to make things more specific and clear.

**Comment by Gaelan** [comment]
@stubailo [GraphQL has support for "subscriptions" out of the box, and FB is open to community ideas on live data.][fbpage] It is probably worth talking to Facebook about this.

[fbpage]: http://graphql.org/blog/subscriptions-in-graphql-and-relay/

**Comment by stubailo** [comment]
Yes, we have talked to them. Note that the meteor approach is specifically about reactive queries, _not_ subscriptions - you don't have to separate your data requirements and your subscriptions, you can just have one big query, some parts of which are reactive.

In short, the current subscription feature in GraphQL is not the thing we are trying to build.
