### ISSUE TITLE
Securing data in GraphQL schemas?

### ISSUE THREAD

**Issue by brylie** [meteor/data#3]
If GraphQL schema may replace the pub/sub approach to template data handling, what will security look like? E.g. some publications perform security checks before returning data to the client. How will this be done with a GraphQL schema?

**Comment by arunoda** [comment]
This is possible with GraphQL too. Check this article: https://medium.com/@clayallsopp/graphql-and-authentication-b73aed34bbeb#.6jiuizphx

Basically, you could authorize inside the GraphQL field resolver. Not sure, how Meteor is going to do it, but there should be a way to do that.

**Comment by batjko** [comment]
I don't see a problem checking for authentication in every resolve() function.
Not sure if this needs to be provided by Meteor as part of the data initiative. It can probably be left to whatever authentication package people prefer at the time.

**Comment by stubailo** [comment]
I think providing an easy path to authentication is exactly the kind of value-add Meteor should be bringing - nobody else will be able to provide a tight integration with a standard accounts system. Of course, it will be optional, but I think it is a good default especially if you are using it in a Meteor app.

This fits with an important theme of the new project: flexible enough to be used anywhere, but extra integrations and cohesion when used as part of the Meteor platform.
