### ISSUE TITLE
Figure out how to run Relay without Babel 6

### ISSUE THREAD

**Issue by stubailo** [meteor/data#7]
It's annoying that you need a specific babel plugin to compile `Relay.QL` template strings at build time. Specifically, you need to:

1. Compile your server
2. Run the introspection query and save the result to a file
3. Pass that result into a Babel 6 plugin to compile your client code
4. Run your client

This has several unfortunate consequences, in particular:

1. You absolutely need to use Babel 6
2. You can't easily develop the client and server in parallel (if one person is working on both) because of the multitude of compilation steps above
3. You can't easily play around with queries in the browser console

It's pretty easy to run the parser at runtime in development mode, and this will make it much easier to work around the drawbacks above.

I should publish this as an NPM package so that you can use `Relay.QL` just like you would use any template string.

**Comment by ramsaylanier** [comment]
Not sure of your progress - but this idea seems to be idea: configuring the GraphQL schema from .babelrc.

https://github.com/facebook/relay/issues/819

**Comment by stubailo** [comment]
@ramsaylanier the goal here is a bit more ambitious. I'd like to run Relay _without Babel entirely_. I think having to set up a specific build toolchain just to use a client library doesn't make sense, and makes it a lot harder for people to adopt.

**Comment by ramsaylanier** [comment]
Ah okay - if we are trying to remove Babel from the entire equation that makes sense.

**Comment by stubailo** [comment]
I believe I have a working version of this: https://github.com/meteor/relay-runtime-query
